name: CI - FastMove API

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/base.txt
          pip install -r requirements/dev.txt
          pip install -r requirements/test.txt

      - name: Formato - Black
        run: black --check app tests

      - name: Import sort - isort
        run: isort --check-only app tests

      - name: Linter - Flake8
        run: flake8 app tests

      - name: Tipado - MyPy
        run: mypy app

      - name: Seguridad - Bandit
        run: bandit -r app

      - name: Ejecutar pruebas
        run: pytest --cov=app --cov-report=xml --cov-report=term-missing

      - name: Subir reporte de cobertura
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          fail_ci_if_error: true
